#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  2 19:58:34 2019

@author: DTroester
"""

import C4Runner
import matplotlib.pyplot as plt
import seaborn as sns

test = 11
height = 6
width = 7
runs = 100000
runner = C4Runner.Runner
tcount = 0
rcount = 0
bcount = 0
rgrid = [0] * height
for i in range(height):
    rgrid[i] = [0]*width
bgrid = [0] * height
for i in range(height):
    bgrid[i] = [0]*width

for i in range(runs):
    result = runner.main()
    result = [height - 1 - result[0],width - 1 - result[1],result[2]]
    test += 1
    if result[2] == 'r':
        rcount += 1
        rgrid[result[0]][result[1]] += 1
    elif result[2] == 'b':
        bcount += 1
        bgrid[result[0]][result[1]] += 1
    else:
        tcount += 1

for i in range(height):
    for j in range(width):
        rgrid[i][j] = rgrid[i][j] * 100.0 / runs

for i in range(height):
    for j in range(width):
        bgrid[i][j] = bgrid[i][j] * 100.0 / runs

rpercent = rcount * 100.0 / runs
bpercent = bcount * 100.0 / runs
tpercent = tcount * 100.0 / runs

print()
print("{} games were played. r won {}% of the games. b won {}% of the games. {}% of the games were tied.".format(runs,rpercent,bpercent,tpercent))

fig = plt.figure(figsize = (20,20))
ax1 = fig.add_subplot(3, 3, 1)
ax2 = fig.add_subplot(3, 3, 2)

sns.heatmap(rgrid, ax=ax1, cmap = "YlGnBu", square=True, cbar_kws={'shrink': .3}, annot=True, annot_kws={'fontsize': 12})
sns.heatmap(bgrid, ax=ax2, cmap = "YlGnBu", square=True, cbar_kws={'shrink': .3}, annot=True, annot_kws={'fontsize': 12})